services:
  backend:
    container_name: backend
    image: gradle:8.14-jdk21
    user: root
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ".:/app"
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database
    dns:
      - 8.8.8.8
      - 8.8.4.4
  database:
    container_name: database
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: sky
    ports:
      - "5432:5432"
    volumes:
      - sky_db_data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:1.75.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
volumes:
  sky_db_data: {}